version: '{branch}.{build}'

configuration:
  - Release
  - Debug

environment:
  matrix:
    - platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_TEMPLATE: Visual Studio 12 2013
      PLATFORM_TOOLSET: v120

    - platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_TEMPLATE: Visual Studio 14 2015
      PLATFORM_TOOLSET: v140

    - platform: Win32
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_TEMPLATE: Visual Studio 15 2017
      PLATFORM_TOOLSET: v141

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      CMAKE_TEMPLATE: Visual Studio 12 2013 Win64
      PLATFORM_TOOLSET: v120

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_TEMPLATE: Visual Studio 14 2015 Win64
      PLATFORM_TOOLSET: v140

    - platform: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_TEMPLATE: Visual Studio 15 2017 Win64
      PLATFORM_TOOLSET: v141

build_script:
  - cmake -G %CMAKE_TEMPLATE% -DCMAKE_INSTALL_PREFIX=t_install .
  - cmake --build . --config %configuration% --target install

after_build:
  - cd t_install
  - 7z a ../json-c.%platform%.%PLATFORM_TOOLSET%.%configuration%.zip *

artifacts:
  - path: json-c.%platform%.%PLATFORM_TOOLSET%.%configuration%.zip
    name: json-c.%platform%.%PLATFORM_TOOLSET%.%configuration%.zip
